<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Available</name>
   <tag></tag>
   <elementGuidId>8f210f6a-1a1d-4c8c-96fe-66cb50db1db2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.rounded-md.\[\&amp;_svg\:not\(\[class\*\=\'text-\'\]\)\]\:text-muted-foreground.data-\[placeholder\]\:text-muted-foreground.shadow-xs.text-sm.whitespace-nowrap.\*\:data-\[slot\=select-value\]\:flex.\*\:data-\[slot\=select-value\]\:items-center.\[\&amp;_svg\]\:pointer-events-none.border-input.justify-between.transition-\[color\,box-shadow\].bg-transparent.border.outline-none.w-full[data-slot=&quot;select-trigger&quot;][aria-autocomplete=&quot;none&quot;][role=&quot;combobox&quot;][dir=&quot;ltr&quot;][type=&quot;button&quot;][data-size=&quot;default&quot;][data-state=&quot;closed&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-md ') and (contains(concat(' ', normalize-space(@class), ' '), ' [&amp;_svg:not([class*='text-'])]:text-muted-foreground ')) and contains(concat(' ', normalize-space(@class), ' '), ' data-[placeholder]:text-muted-foreground ') and contains(concat(' ', normalize-space(@class), ' '), ' shadow-xs ') and contains(concat(' ', normalize-space(@class), ' '), ' text-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and (contains(concat(' ', normalize-space(@class), ' '), ' *:data-[slot=select-value]:flex ')) and (contains(concat(' ', normalize-space(@class), ' '), ' *:data-[slot=select-value]:items-center ')) and contains(concat(' ', normalize-space(@class), ' '), ' [&amp;_svg]:pointer-events-none ') and contains(concat(' ', normalize-space(@class), ' '), ' border-input ') and contains(concat(' ', normalize-space(@class), ' '), ' justify-between ') and contains(concat(' ', normalize-space(@class), ' '), ' transition-[color,box-shadow] ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-transparent ') and contains(concat(' ', normalize-space(@class), ' '), ' border ') and contains(concat(' ', normalize-space(@class), ' '), ' outline-none ') and contains(concat(' ', normalize-space(@class), ' '), ' w-full ') and (@data-slot = 'select-trigger') and (@aria-autocomplete = 'none') and (@role = 'combobox') and (@dir = 'ltr') and (@type = 'button') and (@data-size = 'default') and (@data-state = 'closed')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>389eed79-fb43-4905-8136-d42f422a0aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e8eec5bf-74f9-460a-aba1-36cf42c374e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>66925140-26f7-4cd8-a55d-2bde7e07dbe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-_r_s5_</value>
      <webElementGuid>53b84e2c-9544-49fe-877a-54e0b9554801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>56c863cc-54b2-420a-a56e-e47390e92ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>760517fc-2828-4634-ac74-fcbb56fe4411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>6b0d57f0-1796-465d-87ca-a8854457a9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>595243a0-bec9-4e49-87b6-ae706f71f77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>select-trigger</value>
      <webElementGuid>5eaf7282-846e-48fa-ac0d-423de7e4488d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>03657b8f-2433-4fd4-a7e3-a6f59b8c4a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-input data-[placeholder]:text-muted-foreground [&amp;_svg:not([class*='text-'])]:text-muted-foreground focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive dark:bg-input/30 dark:hover:bg-input/50 flex items-center justify-between gap-2 rounded-md border bg-transparent px-3 py-2 text-sm whitespace-nowrap shadow-xs transition-[color,box-shadow] outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 data-[size=default]:h-9 data-[size=sm]:h-8 *:data-[slot=select-value]:line-clamp-1 *:data-[slot=select-value]:flex *:data-[slot=select-value]:items-center *:data-[slot=select-value]:gap-2 [&amp;_svg]:pointer-events-none [&amp;_svg]:shrink-0 [&amp;_svg:not([class*='size-'])]:size-4 w-full</value>
      <webElementGuid>9e438cc2-9f77-499c-abfe-3f2e7faafcc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Available</value>
      <webElementGuid>c0697474-288e-450e-99a6-ee49e7d885c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c4abc38b5777e8359d701ef5a36c3aa5</value>
      <webElementGuid>8947a32d-c780-4e5d-bb32-a0fc10193f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-md ') and (contains(concat(' ', normalize-space(@class), ' '), ' [&amp;_svg:not([class*='text-'])]:text-muted-foreground ')) and contains(concat(' ', normalize-space(@class), ' '), ' data-[placeholder]:text-muted-foreground ') and contains(concat(' ', normalize-space(@class), ' '), ' shadow-xs ') and contains(concat(' ', normalize-space(@class), ' '), ' text-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and (contains(concat(' ', normalize-space(@class), ' '), ' *:data-[slot=select-value]:flex ')) and (contains(concat(' ', normalize-space(@class), ' '), ' *:data-[slot=select-value]:items-center ')) and contains(concat(' ', normalize-space(@class), ' '), ' [&amp;_svg]:pointer-events-none ') and contains(concat(' ', normalize-space(@class), ' '), ' border-input ') and contains(concat(' ', normalize-space(@class), ' '), ' justify-between ') and contains(concat(' ', normalize-space(@class), ' '), ' transition-[color,box-shadow] ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-transparent ') and contains(concat(' ', normalize-space(@class), ' '), ' border ') and contains(concat(' ', normalize-space(@class), ' '), ' outline-none ') and contains(concat(' ', normalize-space(@class), ' '), ' w-full ') and (@data-slot = 'select-trigger') and (@aria-autocomplete = 'none') and (@role = 'combobox') and (@dir = 'ltr') and (@type = 'button') and (@data-size = 'default') and (@data-state = 'closed')]</value>
      <webElementGuid>2dc0f3a5-3afb-4bac-bca8-5bb14822a8af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-md ') and (contains(concat(' ', normalize-space(@class), ' '), ' [&amp;_svg:not([class*='text-'])]:text-muted-foreground ')) and contains(concat(' ', normalize-space(@class), ' '), ' data-[placeholder]:text-muted-foreground ') and contains(concat(' ', normalize-space(@class), ' '), ' shadow-xs ') and contains(concat(' ', normalize-space(@class), ' '), ' text-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and (contains(concat(' ', normalize-space(@class), ' '), ' *:data-[slot=select-value]:flex ')) and (contains(concat(' ', normalize-space(@class), ' '), ' *:data-[slot=select-value]:items-center ')) and contains(concat(' ', normalize-space(@class), ' '), ' [&amp;_svg]:pointer-events-none ') and contains(concat(' ', normalize-space(@class), ' '), ' border-input ') and contains(concat(' ', normalize-space(@class), ' '), ' justify-between ') and contains(concat(' ', normalize-space(@class), ' '), ' transition-[color,box-shadow] ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-transparent ') and contains(concat(' ', normalize-space(@class), ' '), ' border ') and contains(concat(' ', normalize-space(@class), ' '), ' outline-none ') and contains(concat(' ', normalize-space(@class), ' '), ' w-full ') and (@data-slot = 'select-trigger') and (@aria-autocomplete = 'none') and (@role = 'combobox') and (@dir = 'ltr') and (@type = 'button') and (@data-size = 'default') and (@data-state = 'closed')]</value>
      <webElementGuid>4c686fbe-aa7d-40ac-b270-29df4b1d307f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Available' or . = 'Available')]</value>
      <webElementGuid>0f2ae31f-7209-46b2-b4f9-fa3e82819333</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
