analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3437997,"name"\:"Sample - HR Web App \#3437997","teamId"\:3409903,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3474788,"autoIntegrate"\:false,"sampleProject"\:false,"accountId"\:null}
analytics.team={"id"\:3409903,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
