<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_dropdown_trigger</name>
   <tag></tag>
   <elementGuidId>0d6e6dbe-0b0b-4952-994c-e89aa569f2e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@data-slot = 'dropdown-menu-trigger' and @aria-haspopup = 'menu' and @data-state = 'closed' and @data-testid = 'detail-order-1']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@class and contains(concat(' ', normalize-space(@class), ' '), ' justify-center ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-md ') and contains(concat(' ', normalize-space(@class), ' '), ' text-muted-foreground ') and (@aria-haspopup = 'menu') and (@data-slot = 'dropdown-menu-trigger') and (@type = 'button')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.justify-center.rounded-md.text-muted-foreground[aria-haspopup=&quot;menu&quot;][data-slot=&quot;dropdown-menu-trigger&quot;][type=&quot;button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f391fd3-e12d-4eb5-b614-d6bf25bb93d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>dropdown-menu-trigger</value>
      <webElementGuid>65b83e6e-d145-4e8f-9d79-e0df2c52f144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg:not([class*='size-'])]:size-4 shrink-0 [&amp;_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50 data-[state=open]:bg-muted text-muted-foreground flex size-8</value>
      <webElementGuid>eaa61bb3-a7af-4671-904d-46395a6c7698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8470bd89-42dc-4305-916c-080a6d325a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-_r_l_</value>
      <webElementGuid>2a30bb53-f5e7-435b-a7ae-fe8ca03cbb61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>043417b2-6d43-4a0f-8453-bd0b9931b0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ae638cbe-6768-47fd-bcb4-4168b083195b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>6398a522-7ee8-4846-8b1a-c07d3794b2a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-00a00734186d230ef5d3643388460547</value>
      <webElementGuid>65d47359-4d5b-4dfa-9f08-23acff335ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@class and contains(concat(' ', normalize-space(@class), ' '), ' justify-center ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-md ') and contains(concat(' ', normalize-space(@class), ' '), ' text-muted-foreground ') and (@aria-haspopup = 'menu') and (@data-slot = 'dropdown-menu-trigger') and (@type = 'button')]</value>
      <webElementGuid>c21f18b9-c817-4b37-b593-1a1e032583c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>detail-order-1</value>
      <webElementGuid>838ec6ae-31e8-4a24-b3a5-0a6c13e1791c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@class and contains(concat(' ', normalize-space(@class), ' '), ' justify-center ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-md ') and contains(concat(' ', normalize-space(@class), ' '), ' text-muted-foreground ') and (@aria-haspopup = 'menu') and (@data-slot = 'dropdown-menu-trigger') and (@type = 'button')]</value>
      <webElementGuid>854d4197-fad4-4383-a3c0-c018c1bfc3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'radix-_r_2g_']</value>
      <webElementGuid>6369aab4-d951-4711-becf-22b4b7375fd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
