<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Dine In</name>
   <tag></tag>
   <elementGuidId>bfc03e3a-1639-46ef-a144-af1ccec87a70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-slot=&quot;dialog-trigger&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-slot = 'dialog-trigger']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Dine In&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>97a1b8f3-2a07-42f9-b6f5-1641e239310c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>937f2b0e-85a0-4b9c-ab12-565f207a7fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>912aca9f-9b8a-4b14-bf43-e42647f76d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>391a9903-6568-4d2d-b2e5-1abbb3cc9d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-_r_dq_</value>
      <webElementGuid>59f045aa-0987-480e-9167-1c513a4053b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>8ff9fbcf-17bc-4b52-af0c-c731ad1528ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>dialog-trigger</value>
      <webElementGuid>7d992988-048e-400c-9679-344d284684cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center gap-2 text-sm p-2 w-full rounded-md hover:bg-muted</value>
      <webElementGuid>f3cb0d19-9e6f-43cc-aaf0-89cee876a62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dine In</value>
      <webElementGuid>f5515a05-dd5c-4b82-a34b-7783f93d70b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-32a350b108900b77cc16bfbdb17e5b80</value>
      <webElementGuid>2c1eeaa2-af88-49ff-9a28-3afd58f2e7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-slot = 'dialog-trigger']</value>
      <webElementGuid>8adaf5dc-85b3-45d4-bd06-0505afe7bc4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-slot = 'dialog-trigger']</value>
      <webElementGuid>9da6b944-8b27-4c3e-9889-0c4908d01eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Dine In' or . = 'Dine In')]</value>
      <webElementGuid>0bf58fb4-edba-4746-ba23-c29c940dd689</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
