<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Copy</name>
   <tag></tag>
   <elementGuidId>9a0b92b2-5dae-4857-bb1c-0db0dd4f3119</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.clickable.copy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' clickable ') and contains(concat(' ', normalize-space(@class), ' '), ' copy ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Copy&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19f3043c-bbc5-4149-8bb2-b49b9340afa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>float-right clickable copy</value>
      <webElementGuid>f4bada46-08af-467e-85a5-c363a6d0de99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copy</value>
      <webElementGuid>e0c28173-6214-4f83-a08f-b58c73de7edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-adc022d9a66fc1e2e3275643d47b79b7</value>
      <webElementGuid>a1732092-b39e-42d3-8898-dab5d1512986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' clickable ') and contains(concat(' ', normalize-space(@class), ' '), ' copy ')]</value>
      <webElementGuid>a91092b5-d849-407d-86e1-067de3ccf868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Menu/Order-Checkout/iframe_snap-midtrans</value>
      <webElementGuid>a1a2c85d-9538-4be2-a6d8-dd1bf73ebe56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' clickable ') and contains(concat(' ', normalize-space(@class), ' '), ' copy ')]</value>
      <webElementGuid>d6ca5ffc-45e6-4bc6-b63f-df837cbe68a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Copy' or . = 'Copy')]</value>
      <webElementGuid>881f4c06-d9ed-494f-bdbb-a2fe0a1810f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
