<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_snap-midtrans</name>
   <tag></tag>
   <elementGuidId>57e5db9d-7bbc-4aaa-9591-09d2f8f5df56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#snap-midtrans</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'snap-midtrans']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;popup_1779766115861&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>70c2430a-a389-4925-966a-863eedf73696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://app.sandbox.midtrans.com/snap/v4/popup?origin_host=https://pos.bling.my.id&amp;client_key=SB-Mid-client-NzmXfX28IyoifppF#/</value>
      <webElementGuid>c356b0e2-7a83-46d5-8b8d-76d92b55d821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>snap-midtrans</value>
      <webElementGuid>da92c153-d0ac-434f-9f5a-43454e417b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popup_1779766115861</value>
      <webElementGuid>008d15b6-bc24-4ba9-b5c8-3d9800d4e739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3c679ba776a45a94935bb1a275779b5c</value>
      <webElementGuid>f22b0112-7b2a-49df-bb0e-0757d92c6a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'snap-midtrans']</value>
      <webElementGuid>917a7a39-829d-4b32-8513-04388ce0e360</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'snap-midtrans']</value>
      <webElementGuid>713d887e-b8c5-4e56-8b56-1ec95abeccd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://app.sandbox.midtrans.com/snap/v4/popup?origin_host=https://pos.bling.my.id&amp;client_key=SB-Mid-client-NzmXfX28IyoifppF#/' and @id = 'snap-midtrans' and @name = 'popup_1779766115861']</value>
      <webElementGuid>af61c741-fd98-42d0-b39e-a701dec4c4e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
