<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Virtual account1</name>
   <tag></tag>
   <elementGuidId>7c0d7644-4d2d-436a-b8c9-e8e826617888</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.collapsible-payment--multiple__body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bank_transfer']/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bank_transfer div >> internal:has-text=&quot;Virtual account+1&quot;i >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>621db8b1-8c3d-4692-a1af-f48d8ddf880d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>collapsible-payment--multiple__body</value>
      <webElementGuid>42f21daa-62fb-4d10-bfa2-6075b0611e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Virtual account+1</value>
      <webElementGuid>3f511662-4fcf-4a50-8c18-2838141e43f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bank_transfer&quot;)/div[@class=&quot;collapsible-payment&quot;]/div[@class=&quot;collapsible collapsible-payment--multiple&quot;]/div[@class=&quot;collapse-button collapsible-payment--multiple&quot;]/div[@class=&quot;collapsible-payment--multiple__body&quot;]</value>
      <webElementGuid>af31ed81-cafa-4274-ab7a-2dff051305d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Menu/Order-Checkout/Manual-Scheckout-SPY-v2/iframe_Pay_snap-midtrans</value>
      <webElementGuid>77fa4c73-094f-41e1-8515-e90132e0a685</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bank_transfer']/div/div/div/div</value>
      <webElementGuid>721b1921-4e7d-4b73-8046-b77e970c8d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit/debit card'])[1]/following::div[12]</value>
      <webElementGuid>df548f5d-b62a-40fd-8495-89afaa0a8233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All payment methods'])[1]/following::div[15]</value>
      <webElementGuid>f9519af0-fd19-471d-8e0b-27fdafd884cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GoPay QRIS'])[2]/preceding::div[12]</value>
      <webElementGuid>d1aacc52-a24a-49c3-abb7-f762737caa70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div</value>
      <webElementGuid>89bfeea8-0711-4df4-bec2-8afb9beec3da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Virtual account+1' or . = 'Virtual account+1')]</value>
      <webElementGuid>7eb3d9d0-8f56-4d4c-a58b-d5f29ab57816</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
